SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;

SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `VIDIENTU` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_0900_AI_CI;

USE `VIDIENTU`;

CREATE TABLE IF NOT EXISTS `VIDIENTU`.`ACCOUNTS` (
  `ID_USER` INT NOT NULL AUTO_INCREMENT,
  `ACCOUNT_NO` VARCHAR(500) NOT NULL,
  `OWNER` VARCHAR(60) NOT NULL,
  `BALANCE` DOUBLE NOT NULL,
  `USERNAME`VARCHAR(20) NOT NULL,
  `PASSWORD`VARCHAR(255) NOT NULL,
  `EMAIL`VARCHAR(50) NOT NULL,
  `REWARDS` INT,
  PRIMARY KEY (`ID_USER`)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS `VIDIENTU`.`TRANSACTIONS` (
  `ID_TRANSACTION` INT NOT NULL AUTO_INCREMENT,
  `FROM` VARCHAR(500),
  `TO` VARCHAR(500),
  `AMOUNT` DOUBLE,
  `MESSAGE` VARCHAR(500),
  `TIMESTAMP`DATETIME,
  PRIMARY KEY (`ID_TRANSACTION`)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS `VIDIENTU`.`BLOCK` (
  `ID_TRANSACTION` INT,
  `ID_BLOCK` INT NOT NULL AUTO_INCREMENT,
  `PREHASH` VARCHAR(255) NOT NULL,
  `HASH` VARCHAR(255) NOT NULL,
  `TIMESTAMP`DATETIME,
  PRIMARY KEY (`ID_BLOCK`)
)ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS `VIDIENTU`.`TRANSACTIONS_COIN` (
  `ID_TRANSACTION_COIN` INT NOT NULL AUTO_INCREMENT,
  `FROM` VARCHAR(500),
  `TO` VARCHAR(500),
  `AMOUNT` DOUBLE,
  `TIMESTAMP`DATETIME,
  PRIMARY KEY (`ID_TRANSACTION_COIN`)
) ENGINE = INNODB;

SELECT
  *
FROM
  BLOCK;

SELECT
  *
FROM
  TRANSACTIONS;

SELECT
  *
FROM
  TRANSACTIONS_COIN;