SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `vidientu` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vidientu` ;

-- drop table ACCOUNTS;
-- drop table TRANSACTIONS;
CREATE TABLE IF NOT EXISTS `vidientu`.`ACCOUNTS` (
  `ID_User` INT NOT NULL auto_increment,
  `Account_No` VARCHAR(60) NOT NULL,
  `Owner` VARCHAR(60) NOT NULL,
  `Balance` DOUBLE NOT NULL,
  `Username`VARCHAR(20) NOT NULL,
  `Password`VARCHAR(255) NOT NULL,
  `Email`varchar(50) NOT NULL,
  PRIMARY KEY (`ID_User`)
)
ENGINE = InnoDB;
insert into ACCOUNTS values('1','123','Pham',100,'abc','123','pham@')
select * from ACCOUNTS
CREATE TABLE IF NOT EXISTS `vidientu`.`TRANSACTIONS` (
  `ID_Transaction` INT NOT NULL auto_increment,
  `From` INT NOT NULL,
  `To` INT NOT NULL,
  `Amount` double NOT NULL,
  `DateTime` datetime,
  `PreHash` VARCHAR(255) NOT NULL,
  `Hash` VARBINARY(255) NOT NULL,
  `Notes` VARCHAR(200) ,
  PRIMARY KEY (`ID_Transaction`)
)
ENGINE = InnoDB;

